tango_project/rango/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from . import views

# app_name = 'rango'
# излишне для меня потому что у меня спецификация rango в url если бы её не было то пришлось бы

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.index_about, name='index_about'),
        url(r'^new/$', views.index2, name='index2'),
        url(r'^add_category/$', views.add_category, name='add_category'),
        url(r'^change_category/$', views.change_category, name='change_category'),
        url(r'^change_page/$', views.change_page, name='change_page'),
        url(r'^delete_page/$', views.delete_page, name='delete_page'),

        # слово + дефис + любое их количество до слеша /
        url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),

        # url(r'^register/$', views.register, name='register'),
        # url(r'^login/$', views.user_login, name='login'),
        url(r'^restricted/', views.restricted, name='restricted'),
        url(r'^search/', views.search, name='search'),
        # url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^example/$', views.some_view, name='some_view'),
        url(r'^like_category/$', views.like_category, name='like_category'),
        url(r'^add_profile/$', views.register_profile, name='add_profile'),
        url(r'^profile/(?P<user_name>[\w\-]+)/$', views.profile, name='profile'),
        url(r'^lockid/(?P<lockid>[\w\-]+)/$', views.lockid, name='lockid'),
        url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
        url(r'^auto_add_page/$', views.auto_add_page, name='auto_add_page'),
        url(r'^lock/$', views.lock, name='lock'),
        url(r'^goto/$', views.track_url, name='goto'),
        url(r'^restricted/$', views.restricted, name='restricted'),
]

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     # Examples:
#     # url(r'^$', 'tango_with_django_project_17.views.home', name='home'),
#     # url(r'^blog/', include('blog.urls')),
#     url(r'^rango/', include('rango.urls')),  # ADD THIS NEW TUPLE!
# ]

tango_project/tango_project/urls.py
from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from django.shortcuts import redirect
from django.views.generic.base import RedirectView

# чтобы не откидывала на registartion complete page а на index
# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request):
        return '/rank/add_profile/'


urlpatterns = [
    url(r'^favicon1\.ico$', 'rango.views.my_image'),
    url(r'^favicon\.ico$', 'rango.views.my_image'),
    url(r'^admin/', admin.site.urls),
    # Examples:
    url(r'^$', 'rango.views.index', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #Add in this url pattern to override the default pattern in accounts.
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^rank/', include('rango.urls')),  # ADD THIS NEW TUPLE!
    url(r'^accounts/', include('registration.backends.simple.urls')),
]


# UNDERNEATH your urlpatterns definition, add the following two lines:
# if settings.DEBUG:
if True:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)','serve',{'document_root': settings.MEDIA_ROOT}), )

tango_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()
    date_of_creation = models.DateField(default=timezone.now())
    author = models.ForeignKey(User)
    information = models.CharField(max_length=1000, default="No information present.")
    lock = models.CharField(max_length=100, default="")
    open = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
            # Uncomment if you don't want the slug to change every time the name changes
            if self.id is None:
                    self.slug = slugify(self.name)
            # self.slug = slugify(self.name)

            if not self.id:
                self.date_of_creation = timezone.now()

            if self.views < 0 or self.likes < 0:
                self.views = self.likes = 0
            super(Category, self).save(*args, **kwargs)

    def __str__(self):  #For Python 2, use __str__ on Python 3
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    last_visit = models.DateTimeField(default=timezone.now())
    information = models.CharField(max_length=200, default="")


    def save(self, *args, **kwargs):
        self.modified = timezone.now()
        return super(Page, self).save(*args, **kwargs)

    def __str__(self):      #For Python 2, use __str__ on Python 3
        return self.title


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    # blank = True то есть заполнение по желанию, они могут быть пусты
    website = models.URLField(blank=True)
    # in all profile images being stored in the directory
    #  <workspace>/tango_with_django_project/media/profile_images/.
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __str__(self):
        return self.user.username

tango_project/rango/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Category, Page, UserProfile, User
from .forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from .bing_search import run_query
from .my_random_generate import generate
from django.template.defaultfilters import slugify
from django.utils.html import escape


def my_image(request):
    image_data = open("./static/images/favicon.ico", "rb").read()
    print("open")
    return HttpResponse(image_data, content_type="image/png")


def user_login(request):

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed to request.POST['<variable>'],
        # because the request.POST.get('<variable>') returns None, if the value does not exist,
        # while the request.POST['<variable>'] will raise key error exception
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/rank/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details: {0}, {1}".format(username, password))
            # return HttpResponse("Invalid login details supplied.")
            return render(request, 'rango/login.html', {'message': "Invalid login details supplied."})

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'rango/login.html', {})


def register(request):

    # if request.session.test_cookie_worked():
    #     print(">>>> TEST COOKIE WORKED!")
    #     request.session.delete_test_cookie()

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        # можно было просто написать request.POST
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print(user_form.errors, profile_form.errors)

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
            'rango/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )


@login_required
def add_page(request, category_name_slug):

    try:
        cat = Category.objects.get(slug=category_name_slug)
        if cat.author != request.user:
                raise Http404("You aren't the author of this category!")
    except Category.DoesNotExist:
                # cat = None
                return HttpResponse('This page does not exist! (You should pass existing url of category, but you pass '
                                     + '<strong>' + category_name_slug + '</strong>)')

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                # объект не будет сохранён в базу данных
                # будет только создан
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                # probably better to use a redirect here.
                # Always return an HttpResponseRedirect after successfully dealing
                # with POST data. This prevents data from being posted twice if a
                # user hits the Back button.
                # return HttpResponseRedirect(reverse('index', args=(cat.name,)))

                # я не заметил разницы,с тем что выше
                # так же проверено на кнопке назад
                return category(request, category_name_slug)
        else:
            print(form.errors)
    else:
        form = PageForm()

    context_dict = {'form': form, 'category': cat}

    return render(request, 'rango/add_page.html', context_dict)


def search(request):

    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()

        if query:
            # Run our Bing function to get the results list!
            result_list = run_query(query)

    return render(request, 'rango/search.html', {'result_list': result_list})


@login_required
def change_category(request):
    errors = []
    if request.method == 'GET':
        information = request.GET['information']
        catid = request.GET['cat_id']

        if len(information) > 1000 or information == "":
            errors.append("Please make information with length less than 1000 characters and not empty.")
        cat = Category.objects.filter(id=catid)
        if cat.count() > 0 and len(errors)==0:
            cat = cat[0]
            if cat.author == request.user:
                information = escape(information)
                cat.information = information
                cat.save()
            else:
                errors.append("Who are you?")
        else:
            errors.append("This category doesn't exist")

        if len(errors) == 0:
            return HttpResponse("ok")

    else:
        errors.append("Please, use form.")

    return HttpResponse(errors[0])


@login_required
def change_page(request):
    errors = []
    if request.method == 'GET':
        information = request.GET['information']
        catid = request.GET['cat_id']
        page_id = request.GET['page_id']

        if len(information) > 200 or information == "":
            errors.append("Please make information with length less than 200 characters and not empty.")
        cat = Category.objects.filter(id=catid)
        page = Page.objects.filter(id=page_id, category=cat)
        if cat.count() > 0 and page.count() > 0 and len(errors) == 0:
            cat = cat[0]
            page = page[0]
            if cat.author == request.user:
                information = escape(information)
                page.information = information
                page.save()
            else:
                errors.append("Who are you?")
        else:
            errors.append("This page or category doesn't exist. Are you hacker?")

        if len(errors) == 0:
            return HttpResponse("ok")

    else:
        errors.append("Please, use form.")

    return HttpResponse(errors[0])


@login_required
def delete_page(request):
    if request.method == 'GET':
        page_id = request.GET['page_id']
        page = Page.objects.filter(id = page_id)[0]
        if page.category.author == request.user:
            page.delete()
        else:
            HttpResponse("You are not the owner!")
        return HttpResponse("ok")
    else:
        return HttpResponse("Please use the close button!")


@login_required
def add_category(request):
    errors = []
    if request.method == 'POST':
        name = request.POST['name']

tango_project/templates/rango/about.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}About{% endblock %}


{% block body_block %}

    <div class="page-header">
                <h1>About</h1>
            </div>
    <p style="color: red"> Вы заходили к нам: {{ visits }} раза</p>

    <div class="panel panel-primary">
      <!-- Default panel contents -->
      <div class="panel-heading">Current affairs</div>
      <div class="panel-body">
        <p>Все необходимые дела</p>
      </div>

      <!-- List group -->
      <ul class="list-group">
        <li class="list-group-item list-group-item-info">Дописать блок после блока категории</li>
        <li class="list-group-item list-group-item-info">Elastic посмотреть</li>
        <li class="list-group-item list-group-item-info">Добавить изменения страниц</li>
        <li class="list-group-item list-group-item-info">Добавить замочки, чтобы в профили было понятно что блок самому user</li>
        <li class="list-group-item list-group-item-info">Валидацию проверить</li>
      </ul>
    </div>

{% endblock %}

tango_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Add category{% endblock %}


{% block body_block %}

        <!--<form id="category_form" method="post" action="{% url 'add_category' %}">-->
        <!--<h2 class="form-signin-heading">Add category</h2>-->
            <!--{% csrf_token %}-->
            <!--{% for hidden in form.hidden_fields %}-->
                <!--{{ hidden }}-->
            <!--{% endfor %}-->

            <!--{% for field in form.visible_fields %}-->
                <!--{{ field.errors }}-->
                <!--{{ field.help_text }}-->
                <!--{{ field }}-->
            <!--{% endfor %}-->
            <!--<button class="btn btn-primary" type="submit" name="submit">Create Category</button>-->
        <!--</form>-->

        <div class="page-header">
                <h3>User {{ user.username }} :: <small>Add Category</small></h3>
        </div>

        <ul class="list-group">
        {% for error in errors %}
              <li class= "list-group-item list-group-item-danger">  {{ error }}</li>
        {% endfor %}
        </ul>

        <form class="form-horizontal" id="category_form" method="post" action="{% url 'add_category' %}">
            {% csrf_token %}
          <div class="form-group">
            <label for="id_name" class="col-sm-2 control-label">Name: </label>
            <div class="col-sm-10">
              <input type="text" id="id_name" maxlength="50" class="form-control" name="name" placeholder="Category name">
            </div>
          </div>
            <div class="form-group">
            <label for="id_information" class="col-sm-2 control-label">Information: </label>
            <div class="col-sm-10">
              <textarea class="form-control" name="information" rows="5" id="id_information" maxlength="1000" placeholder="Category description"></textarea>
            </div>
          </div>

          <div class="form-group">

            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-lg btn-primary btn">
                  <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                  Make</button>
            </div>
          </div>
        </form>

        <div class="alert alert-warning" role="alert">

<span class="helptext">
  <ul>
    <li><strong>Category name</strong> should be simple.(Less than 50 characters, but more than 3.)</li>
    <li><strong>Category information</strong> should be also simple.(Less than 1000 characters.)</li>
  </ul>
</span>
</div>


        <!--<form id="category_form" method="post" action="/rank/add_category/">-->
        <!--<h2 class="form-signin-heading">Add category</h2>-->
            <!--<input type='hidden' name='csrfmiddlewaretoken' value='e1EHX5IxT0j3qvAuqIh7tsQXD9dydvYP' />-->

                <!--<input id="id_views" name="views" type="hidden" value="0" />-->

                <!--<input id="id_likes" name="likes" type="hidden" value="0" />-->

                <!--<input id="id_slug" maxlength="140" name="slug" type="hidden" />-->




                <!--Please enter the category name.-->
                <!--<input id="id_name" maxlength="128" name="name" type="text" />-->


                <!--Please enter the category information-->
                <!--<input id="id_information" maxlength="1000" name="information" type="text" />-->

            <!--<button class="btn btn-primary" type="submit" name="submit">Create Category</button>-->
        <!--</form>-->

{% endblock %}

tango_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% load staticfiles %}
{% load i18n %}

{% block title %}Add page{% endblock %}


{% block body_block %}
{% if category %}
        <div class="page-header">
                <h3>User <small>{{ user.username }}</small> :: Category <small><a href="{% url 'category' category.slug %}"> {{category.name}}</a></small> :: Add <small>Page</small></h3>
        </div>

        <ul class="list-group">
        {% for error in errors %}
              <li class= "list-group-item list-group-item-danger">  {{ error }}</li>
        {% endfor %}
        </ul>

        <form class="form-horizontal" id="category_form" method="post" action="{% url 'add_page' category.slug %}">
            {% csrf_token %}

            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    <div class="fieldWrapper">
                        {{ error }}
                    </div>
                {% endfor %}
              {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                    </div>
                {% endfor %}
            </div>
            {% endif %}

            <input id="id_views" name="views" type="hidden" value="0" />


            <!--Please enter the title of the page.<br/>-->
            <!--<input id="id_title" maxlength="128" name="title" type="text" /><br/>-->


            <!--Please enter the URL of the page.<br/>-->
            <!--<input id="id_url" maxlength="200" name="url" type="url" /><br/>-->

            <!--<br/>-->
            <!--<input id="id_information" maxlength="200" name="information" type="text" /><br/>-->

          <div class="form-group">
            <label for="id_title" class="col-sm-2 control-label">Name: </label>
            <div class="col-sm-10">
              <input type="text" id="id_title" maxlength="128" minlength="3" class="form-control" name="title" placeholder="Page name">
            </div>
          </div>
            <div class="form-group">
            <label for="id_url" class="col-sm-2 control-label">Url: </label>
            <div class="col-sm-10">
              <input type="url" id="id_url" class="form-control" name="url" placeholder="Page URL">
            </div>
          </div>
            <div class="form-group">
            <label for="id_information" class="col-sm-2 control-label">Information: </label>
            <div class="col-sm-10">
              <textarea class="form-control" name="information" rows="2" id="id_information" maxlength="200" placeholder="Page description"></textarea>
            </div>
          </div>

          <div class="form-group">

            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn-primary btn">
                  <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                  Make</button>
            </div>
          </div>
        </form>

        <div class="alert alert-warning" role="alert">

<span class="helptext">
  <ul>
      <li><strong>Page URL</strong> should be <strong>NOT HTTPS!</strong></li>
      <li><strong>Page name</strong> should be simple.(Less than 128 characters, but more than 3.)</li>
    <li><strong>Page information</strong> should be also simple.(Less than 200 characters.)</li>
  </ul>
</span>
</div>
{%  else %}
                <p>This is category does not exist.</p>
{%  endif %}
{% endblock %}

tango_project/templates/rango/base.html
<!DOCTYPE html>

{% load staticfiles %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src='{% static "js/jquery-1.11.1.js" %}'></script>
<script src='{% static "js/rango-jquery.js" %}'></script>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "js/rango-ajax.js" %}'></script>

{% load rango_extras %}

<html lang="en">
  <head>
    <link rel="shortcut icon" href='{% static "images/favicon.ico" %}'>
    <link rel="shortcut icon" href='{% static "images/favicon.ico" %}' type="image/x-icon">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="icon" href="http://getbootstrap.com/favicon.ico">-->

    <title>Rank {% block title %}{% endblock %}</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid" style="background-color:#373346;">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="{% url 'home' %}">
              RankedList
              {% if user.is_authenticated %}
                :
              <a class="navbar-brand"  href="{% url 'profile' user.username %}">
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                  {{ user.username }}</a>
              {% endif %}
          </a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <!--<li><a href="{% url 'search' %}?next=/rango/">-->
                            <!--<span class="glyphicon glyphicon-search" aria-hidden="true"></span>-->
                            <!--Search</a></li>-->
                <li><a class="mylink" href="{% url 'index' %}">
                    <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                    Home
                </a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'add_category' %}">
                            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                            Add a New Category</a></li>
                        <li><a href="{% url 'restricted' %}">Restricted Page</a></li>
                        <li><a href="{% url 'auth_password_change' %}">Change password</a></li>
                        <li><a href="{% url 'auth_logout' %}?next={% url 'home' %}">
                            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
                            Logout</a></li>

                    {% else %}
                        <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                        <li><a href="{% url 'auth_login' %}">

                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            Login
                        </a></li>
                        <li><a href="{% url 'restricted' %}">Restricted Page</a></li>
                    {% endif %}
                                <li><a href="{% url 'index_about' %}">
                                    About
                                </a></li>

              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}
            <ul class="nav nav-list">
            <li class="nav-header">Find a Category</li>
                <form>
                    <label></label>
                    <li><input  class="search-query span10" type="text" name="suggestion" value="" id="suggestion" /></li>
                </form>
            </ul>


    <div id="cats">
    </div>
                    {% get_category_list category %}
                {% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block body_block %}{% endblock %}
                </div>
        </div>
      </div>
    </div>
    <!-- http://getbootstrap.com/examples/dashboard/# it's template page -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

tango_project/templates/rango/category_list.html
<ul class="nav nav-sidebar">
{% if cat_list %}
    {% for c in cat_list %}
        <!--<li><a href="{% url 'category'  c.slug %}">{{ c.name }}</a></li>-->
        <li  class="active" role="presentation">
            <a href="{% url 'category'  c.slug %}">{{ c.name }}</a>
        </li>
    {% endfor %}
{% else %}
    <li ><strong>There are no categories.</strong></li>
{% endif %}
</ul>

tango_project/templates/rango/cats.html
<ul class="nav nav-sidebar">
{% if cats %}
    {% for c in cats %}
        <!--<li><a href="{% url 'category'  c.slug %}">{{ c.name }}</a></li>-->
        {% if c == act_cat %} <li  class="active" > {% else  %} <li>{% endif %}
            <a href="{% url 'category'  c.slug %}">{{ c.name }}</a></li>
    {% endfor %}
{% else %}
    <li> <strong >There are no category present.</strong></li>
{% endif %}
</ul>

tango_project/templates/rango/login.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Login{% endblock %}


{% block body_block %}

        {% if message %}
            <strong style="color: red">{{ message }}</strong>
        {% endif %}

        <form id="login_form" method="post" action="{% url 'login' %}">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>

{% endblock %}

tango_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Restricted{% endblock %}


{% block body_block %}

<div class="alert alert-success" role="alert">
    Since you're logged in, you can see this text!
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>

</div>

{% endblock %}